### ISSUE TITLE
AttributeError Nonetype for 'job_id'

### ISSUE THREAD

**Issue by willardgtan** [camelot-dev/excalibur#11]
Here's the print out of the problem.  I'm getting a 500 internal server error.  I'm in python 3.7.  Camelot works fine for me (I can parse, read, export no problems).  Just have a problem with running Excalibur. 

* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [06/Nov/2018 21:30:22] "GET / HTTP/1.1" 302 -
[2018-11-06 21:30:22,663] ERROR in app: Exception on /files [GET]
Traceback (most recent call last):
  File "d:\python3.7\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python3.7\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python3.7\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python3.7\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python3.7\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python3.7\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\python3.7\lib\site-packages\excalibur\www\views.py", line 39, in files
    'job_id': job.job_id,
**AttributeError: 'NoneType' object has no attribute 'job_id'**
-----------------------------------------------------------------------------------------
Here's the code that contains the 'job_id' line 39 from the www\views.py file

@views.route('/files', methods=['GET', 'POST'])
def files():
    if request.method == 'GET':
        files_response = []
        session = Session()
        for file in session.query(File).order_by(File.uploaded_at.desc()).all():
            job = session.query(Job).filter(Job.file_id == file.file_id).order_by(Job.started_at.desc()).first()
            files_response.append({
                'file_id': file.file_id,
                **'job_id': job.job_id,**
                'uploaded_at': file.uploaded_at.strftime('%Y-%m-%dT%H:%M:%S'),
                'filename': file.filename
            })

------------------------------------------------------------------------------------------

Any thoughts or am I making some stupid mistakes here?

**Comment by willardgtan** [comment]
The version / download I'm using is excalibur-win-v0.2.1.zip

I'm using Camelot Camelot: PDF Table Extraction for Humans
Release v0.3.2

**Comment by vinayak-mehta** [comment]
@willardgtan Thanks for the detailed report! I think this is happening because you didn't start an extraction job after uploading a file and creating an extraction rule. Sorry, this shouldn't raise an exception and is a bug. I'll push a fix today.

**Comment by vinayak-mehta** [comment]
@willardgtan Meanwhile, you can do a `excalibur resetdb` and it should work.

**Comment by willardgtan** [comment]
excalibur resetdb did the trick!  Please add that to the Docs if you can.  Made my day!

**Comment by sandeepraizada** [comment]
Thank Vinayak. That helped but I am using a fie that identified a table in the pdf... however using this interface i get a message as follows:
ERROR:root:'Table' object has no attribute '_bbox'
Traceback (most recent call last):
  File "/home/sandeep/anaconda3/lib/python3.6/site-packages/excalibur/tasks.py", line 96, in split
    x1, y1, x2, y2 = tables[0]._bbox
AttributeError: 'Table' object has no attribute '_bbox'
Refresh does not change anything... if i click on excalibur then i get this msg back
"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

**Comment by sandeepraizada** [comment]
I noticed a pointer to using the rules and the jobs menu... unfortunately for me these are not select-able after uploading a document.

**Comment by vinayak-mehta** [comment]
> ERROR:root:'Table' object has no attribute '_bbox'

@sandeepraizada Looks like a separate issue. Would it be possible for you to upload the PDF you're trying to extract tables from? Also, are you using the latest version for Camelot? You don't need to install it separately, it is installed with `pip install excalibur-py`.

**Comment by vinayak-mehta** [comment]
@sandeepraizada Please file a separate issue with the PDF.

**Comment by sandeepraizada** [comment]
I have the link to the document in my previous mail. But sure understand and will file a separate issue on this. Thanks for your response.
