### ISSUE TITLE
Ghostscript Error, Stuck in Processing 

### ISSUE THREAD

**Issue by arky** [camelot-dev/excalibur#117]
<details>
<summary>
Using the latest master, we can not extract data on latest Ubuntu 64 (LTS). The Excalibur is stuck in 'Processing  Step'.

```
127.0.0.1 - - [06/Aug/2020 12:54:49] "GET /workspaces/eee2199b-6de1-4d36-8131-abc25fcca6cf HTTP/1.1" 200 -
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
ERROR:root:-100
Traceback (most recent call last):
  File "/media/arky/DevDrive/Code/Camelot-dev/excalibur/.venv/lib/python3.8/site-packages/excalibur_py-0.4.3-py3.8.egg/excalibur/tasks.py", line 56, in split
    with Ghostscript(*gs_call, stdout=null) as gs:
  File "/media/arky/DevDrive/Code/Camelot-dev/excalibur/.venv/lib/python3.8/site-packages/camelot_py-0.8.2-py3.8.egg/camelot/ext/ghostscript/__init__.py", line 90, in Ghostscript
    return __Ghostscript(
  File "/media/arky/DevDrive/Code/Camelot-dev/excalibur/.venv/lib/python3.8/site-packages/camelot_py-0.8.2-py3.8.egg/camelot/ext/ghostscript/__init__.py", line 39, in __init__
    rc = gs.init_with_args(instance, args)
  File "/media/arky/DevDrive/Code/Camelot-dev/excalibur/.venv/lib/python3.8/site-packages/camelot_py-0.8.2-py3.8.egg/camelot/ext/ghostscript/_gsprint.py", line 174, in init_with_args
    raise GhostscriptError(rc)
127.0.0.1 - - [06/Aug/2020 12:54:50] "GET /workspaces/eee2199b-6de1-4d36-8131-abc25fcca6cf HTTP/1.1" 200 -
127.0.0.1 - - [06/Aug/2020 12:54:51] "GET /workspaces/eee2199b-6de1-4d36-8131-abc25fcca6cf HTTP/1.1" 200 -
127.0.0.1 - - [06/Aug/2020 12:54:51] "GET /workspaces/eee2199b-6de1-4d36-8131-abc25fcca6cf HTTP/1.1" 200 -
127.0.0.1 - - [06/Aug/2020 12:54:52] "GET /workspaces/eee2199b-6de1-4d36-8131-abc25fcca6cf HTTP/1.1" 200 -

```
</summary>
![Screenshot from 2020-08-06 12-58-42](https://user-images.githubusercontent.com/808895/89496463-96c17e80-d7e4-11ea-89f3-91e8e8ad9035.png)

</details>

**Comment by Sharas-** [comment]
web interface gets stuck in infinite refresh loop when extracting any PDF.

**Comment by aakashlpin** [comment]
Was trying to Dockerize and host `excalibur` and ran into this same issue. This makes the web interface non-deployable as well.

**Comment by vinayak-mehta** [comment]
Thanks for working on the PR! I'm getting closer to ghostscript in terms of todos and will try to look into this issue and the associated PR today.

**Comment by michellebao** [comment]
Still running into the infinite refresh loop error :(

**Comment by michellebao** [comment]
^^ Nevermind, resolved by using the version on master.

**Comment by michellebao** [comment]
^^ Nevermind, resolved by cloning what was on master instead of using the executable from latest release.

**Comment by evan54** [comment]
experiencing the same issue on Windows, installed Ghostscript using conda... any tips?

excalibur version 0.4.3
camelot version 0.8.2
the ghostscript library returns "Library\bin\gsdll64.dll"

let me know if you need other info that would be helpful

tried installing from source as well but didn't make a difference

**Comment by TomProvence** [comment]
> Thanks for working on the PR! I'm getting closer to ghostscript in terms of todos and will try to look into this issue and the associated PR today.

Hey brother,have you fixed this exception with camelot.ext.ghostscript._gsprint.GhostscriptError: -100? I had meet this problem when I try to deal with  two or more files at the same time

**Comment by vinayak-mehta** [comment]
I'll look into this in the next couple of months.

**Comment by Oaklight** [comment]
any update?

**Comment by TomProvence** [comment]
你好！邮件已经收到，我会尽快回复。谢谢

**Comment by munish0838** [comment]
Any possible solution yet?

**Comment by TomProvence** [comment]
你好！邮件已经收到，我会尽快回复。谢谢

**Comment by arky** [comment]
This project is no longer actively maintained.

**Comment by munish19** [comment]
> This project is no longer actively maintained.

Agreed, but still is there a workaround or a probable solution anyone came up with?
