### ISSUE TITLE
Python 3.8 Fail to initdb Excalibur 0.4.3

### ISSUE THREAD

**Issue by kylelt** [camelot-dev/excalibur#144]
After installing excalibur ( Already have a working camelot installation)

`PS C:\Users\klewer> python.exe --version
Python 3.8.0`

`PS C:\Users\klewer> python -m camelot --version
__main__.py, version 0.10.1`

`PS C:\Users\klewer> python -m excalibur --version
__main__.py, version 0.4.3`

I tried to initdb, the following exception was raised:

`PS C:\Users\klewer> excalibur initdb
Traceback (most recent call last):
  File "c:\users\klewer\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\klewer\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\klewer\AppData\Local\Programs\Python\Python38\Scripts\excalibur.exe\__main__.py", line 4, in <module>
  File "c:\users\klewer\appdata\local\programs\python\python38\lib\site-packages\excalibur\cli.py", line 10, in <module>
    from .tasks import split, extract
  File "c:\users\klewer\appdata\local\programs\python\python38\lib\site-packages\excalibur\tasks.py", line 13, in <module>
    from camelot.ext.ghostscript import Ghostscript
ModuleNotFoundError: No module named 'camelot.ext'
PS C:\Users\klewer> python3.exe`

To fix this in my environment, 

I changed the line:

https://github.com/camelot-dev/excalibur/blob/97eed2654bd8e842b38250417c644c77d0155b7e/excalibur/tasks.py#L9

to 
`from ghostscript import Ghostscript`

This worked in my environment, I do not know the implications for all environments. 

Thanks for your time, and the library it has been very helpful.

**Comment by designgrill** [comment]
This same issue happens on macOS as well. The change helped. Thanks, @kylelt!

**Comment by nitsujri** [comment]
Also same, thanks for the help!

**Comment by Sargastico** [comment]
Same issue on happens on ubuntu, tested on: `Linux ubuntu 5.11.0-36-generic`. The fix by @kylelt works! Cheers!

**Comment by jbsilva** [comment]
Same in Arch Linux (5.14.12-arch1-1) with Python 3.9

The fix worked.

**Comment by bosd** [comment]
@MartinThoma , @vinayak-mehta Can you create a pr from this fork and merge this?
cc: @arky  Do you have super powers here?

**Comment by arky** [comment]
> @MartinThoma , @vinayak-mehta Can you create a pr from this fork and merge this? cc: @arky Do you have super powers here?

@vinayak-mehta is main maintainer here.

**Comment by raosudheesh** [comment]
> excalibur initdb

Traceback (most recent call last):
  File "/home/bro/.local/bin/excalibur", line 5, in <module>
    from excalibur.cli import cli
  File "/home/bro/.local/lib/python3.10/site-packages/excalibur/cli.py", line 6, in <module>
    from . import settings, __version__
  File "/home/bro/.local/lib/python3.10/site-packages/excalibur/settings.py", line 8, in <module>
    from . import configuration as conf
  File "/home/bro/.local/lib/python3.10/site-packages/excalibur/configuration.py", line 4, in <module>
    from backports.configparser import ConfigParser
  File "/home/bro/.local/lib/python3.10/site-packages/backports/configparser/__init__.py", line 130, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

is this fixed?
