### ISSUE TITLE
ImportError: cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by SteffRainville** [camelot-dev/excalibur#157]
pip installed excalbur-py under Python 3.10.4 in Windows 11

Had the configparser error
Upgraded to 5.2.0 as described in issue 151

Now have  ImportError: cannot import name 'escape' from 'jinja2' error when trying to "excalibur initdb"

**Comment by giiyms** [comment]
How do you upgrade to flask v2?

**Comment by SteffRainville** [comment]
Modify the requirements.txt file
Flask==2.1.1

**Comment by alesrosina** [comment]
You can also do
```sh
pip install flask -U
```

And that should work.

**Comment by sd3ntato** [comment]
hi

I applied the suggested changes in https://github.com/camelot-dev/excalibur/pull/183, then i did
```
python3.8 -m venv .venv38
source .venv38/bin/activate
pip install .
excalibur initdb
excalibur webserver
```

and got the app running, but then when I uploaded a pdf I got this error:
```
ERROR:root:PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.
Traceback (most recent call last):
  File "/Users/valeriomariani/Desktop/test_excalibur/excalibur/.venv38/lib/python3.8/site-packages/excalibur/tasks.py", line 22, in split
    extract_pages, total_pages = get_pages(file.filepath, file.pages)
  File "/Users/valeriomariani/Desktop/test_excalibur/excalibur/.venv38/lib/python3.8/site-packages/excalibur/utils/task.py", line 29, in get_pages
    infile = PdfFileReader(inputstream, strict=False)
  File "/Users/valeriomariani/Desktop/test_excalibur/excalibur/.venv38/lib/python3.8/site-packages/PyPDF2/_reader.py", line 1974, in __init__
    deprecation_with_replacement("PdfFileReader", "PdfReader", "3.0.0")
  File "/Users/valeriomariani/Desktop/test_excalibur/excalibur/.venv38/lib/python3.8/site-packages/PyPDF2/_utils.py", line 369, in deprecation_with_replacement
    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))
  File "/Users/valeriomariani/Desktop/test_excalibur/excalibur/.venv38/lib/python3.8/site-packages/PyPDF2/_utils.py", line 351, in deprecation
    raise DeprecationError(msg)
PyPDF2.errors.DeprecationError: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.
```

can anyone help me out with this?
