### ISSUE TITLE
Error during `excalibur initdb` on Windows 10

### ISSUE THREAD

**Issue by js333031** [camelot-dev/excalibur#167]
```

C:\Users\user\Documents\MLReportParser>excalibur initdb
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\excalibur.exe\__main__.py", line 4, in <module>  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\excalibur\cli.py", line 7, in <module>
    from . import __version__, settings
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\excalibur\settings.py", line 6, in <module>
    from sqlalchemy import create_engine, exc
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\__init__.py", line 12, in <module>
    from sqlalchemy.sql import (
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\__init__.py", line 7, in <module>
    from sqlalchemy.sql.expression import (
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\expression.py", line 32, in <module>
    from sqlalchemy import util, exc
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\__init__.py", line 7, in <module>
    from .compat import callable, cmp, reduce, defaultdict, py25_dict, \
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 202, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'

C:\Users\user\Documents\MLReportParser>pip upgrade
ERROR: unknown command "upgrade"

C:\Users\user\Documents\MLReportParser>
```

**Comment by chriscarrollsmith** [comment]
I am getting:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\chris\.virtualenvs\excalibur-lqfZNoys\Scripts\excalibur.exe\__main__.py", line 4, in <module>
  File "C:\Users\chris\.virtualenvs\excalibur-lqfZNoys\Lib\site-packages\excalibur\cli.py", line 6, in <module>
    from . import settings, __version__
  File "C:\Users\chris\.virtualenvs\excalibur-lqfZNoys\Lib\site-packages\excalibur\settings.py", line 8, in <module>
    from . import configuration as conf
  File "C:\Users\chris\.virtualenvs\excalibur-lqfZNoys\Lib\site-packages\excalibur\configuration.py", line 4, in <module>
    from backports.configparser import ConfigParser
  File "C:\Users\chris\.virtualenvs\excalibur-lqfZNoys\Lib\site-packages\backports\configparser\__init__.py", line 130, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (C:\Users\chris\AppData\Local\Programs\Python\Python312\Lib\collections\__init__.py)
