### ISSUE TITLE
ImportError: cannot import name 'TableList'

### ISSUE THREAD

**Issue by fengyuxl** [camelot-dev/excalibur#38]
C:\Program Files\gs\gs9.26\bin>excalibur initdb
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\excalibur.exe\__main__.py", line 5, in
<module>
  File "c:\programdata\anaconda3\lib\site-packages\excalibur\cli.py", line 10, i
n <module>
    from .tasks import split, extract
  File "c:\programdata\anaconda3\lib\site-packages\excalibur\tasks.py", line 11,
 in <module>
    from camelot.core import TableList
ImportError: cannot import name 'TableList'

**Comment by fengyuxl** [comment]
ERROR:root:local variable 'LTObject' referenced before assignment
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\wxl\lib\site-packages\excalibur\tasks.py",
 line 64, in split
    save_page(file.filepath, page)
  File "c:\programdata\anaconda3\envs\wxl\lib\site-packages\excalibur\utils\task
.py", line 65, in save_page
    lttextlh = get_text_objects(layout, ltype="lh")
  File "c:\programdata\anaconda3\envs\wxl\lib\site-packages\camelot\utils.py", l
ine 728, in get_text_objects
    if isinstance(obj, LTObject):

**Comment by vinayak-mehta** [comment]
@fengyuxl Are these both separate errors? You can try [this fix](https://github.com/socialcopsdev/camelot/issues/142#issuecomment-437414730) for the first. The second one looks similar to #41.
