### ISSUE TITLE
Staying in refresh page and not displaying document

### ISSUE THREAD

**Issue by VenkatNaveenM** [camelot-dev/excalibur#51]
127.0.0.1 - - [08/May/2019 17:29:26] "GET /workspaces/35dd602d-2eec-44e7-a51f-36f6b4e4862b HTTP/1.1" 200 -
ERROR:root:exception: access violation writing 0x0E80C1B0
Traceback (most recent call last):
  File "c:\users\naveen\appdata\local\programs\python\python37-32\lib\site-packages\excalibur\tasks.py", line 44, in split
    with Ghostscript(*gs_call, stdout=null) as gs:
  File "c:\users\naveen\appdata\local\programs\python\python37-32\lib\site-packages\camelot\ext\ghostscript\__init__.py", line 93, in Ghostscript
    stderr=kwargs.get('stderr', None))
  File "c:\users\naveen\appdata\local\programs\python\python37-32\lib\site-packages\camelot\ext\ghostscript\__init__.py", line 39, in __init__
    rc = gs.init_with_args(instance, args)
  File "c:\users\naveen\appdata\local\programs\python\python37-32\lib\site-packages\camelot\ext\ghostscript\_gsprint.py", line 167, in init_with_args
    rc = libgs.gsapi_init_with_args(instance, len(argv), c_argv)
OSError: exception: access violation writing 0x0E80C1B0

**Comment by kaitlynbartley** [comment]
I'm also having this problem. Downloaded Excalibur today and it just stays on the refresh page without displaying the workspace. I'm not seeing any errors, though, either in the command line or when I inspect the page source console.
