### ISSUE TITLE
RuntimeError: Please make sure that Ghostscript is installed (Tried all closed issues but no use)

### ISSUE THREAD

**Issue by VenkatNaveenM** [camelot-dev/excalibur#52]
<img width="905" alt="Capture" src="https://user-images.githubusercontent.com/41520213/57456871-0b2d0b00-728c-11e9-97c1-6542533e8cf8.PNG">

**Comment by VenkatNaveenM** [comment]
* Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [09/May/2019 18:53:08] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [09/May/2019 18:53:08] "GET /files HTTP/1.1" 200 -
127.0.0.1 - - [09/May/2019 18:53:15] "POST /files HTTP/1.1" 200 -
127.0.0.1 - - [09/May/2019 18:53:16] "GET /workspaces/5db1e78a-64a6-4b2a-a48d-576a2fddc834 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "c:\users\vmedaram\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\vmedaram\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vmedaram\AppData\Local\Programs\Python\Python37-32\Scripts\excalibur.exe\__main__.py", line 5, in <module>
  File "c:\users\vmedaram\appdata\local\programs\python\python37-32\lib\site-packages\excalibur\cli.py", line 10, in <module>
    from .tasks import split, extract
  File "c:\users\vmedaram\appdata\local\programs\python\python37-32\lib\site-packages\excalibur\tasks.py", line 13, in <module>
    from camelot.ext.ghostscript import Ghostscript
  File "c:\users\vmedaram\appdata\local\programs\python\python37-32\lib\site-packages\camelot\ext\ghostscript\__init__.py", line 24, in <module>
    from . import _gsprint as gs
  File "c:\users\vmedaram\appdata\local\programs\python\python37-32\lib\site-packages\camelot\ext\ghostscript\_gsprint.py", line 229, in <module>
    raise RuntimeError('Please make sure that Ghostscript is installed')
RuntimeError: Please make sure that Ghostscript is installed
Traceback (most recent call last):
  File "excalibur\executors\sequential_executor.py", line 12, in execute_command
  File "subprocess.py", line 341, in check_call
subprocess.CalledProcessError: Command '['excalibur', 'run', '--task', 'split', '--uuid', '5db1e78a-64a6-4b2a-a48d-576a2fddc834']' returned non-zero exit status 1.

**Comment by vinayak-mehta** [comment]
Please make sure you have the correct ghostscript for your OS (32 / 64 bit).
