### ISSUE TITLE
Unable to process PDFs, throws GhostscriptError: -100 on refresh page (mac OS)

### ISSUE THREAD

**Issue by ac-asks** [camelot-dev/excalibur#61]
I've been trying to work on this by forking the repository by duplicating it and setting it to private first via instructions from top answer here (https://stackoverflow.com/questions/10065526/github-how-to-make-a-fork-of-public-repository-private). I have been getting a GhostScript error on a mac OSX.

I am using:
Python 3.7
GPL Ghostscript 9.27 [via homebrew]
opencv: stable 4.1.0 (bottled) [via homebrew]
numpy 1.14.5

I'm simply trying to run it locally via flask run and have already set up my own mySQL database as per instructions. It throws the error when I upload the PDF and try to go to the next page (makes it to the refresh page then throws the error). 

127.0.0.1 - - [09/Jul/2019 09:14:01] "GET /static/css/vendor/jquery-ui.structure.min.css HTTP/1.1" 200 -
127.0.0.1 - - [09/Jul/2019 09:14:01] "GET /static/css/workspace.css HTTP/1.1" 200 -
127.0.0.1 - - [09/Jul/2019 09:14:01] "GET /static/js/vendor/jquery.selectareas.min.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Jul/2019 09:14:01] "GET /static/js/workspace.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Jul/2019 09:14:01] "GET /static/js/vendor/jquery-ui.min.js HTTP/1.1" 200 -
**GPL Ghostscript 9.27: Unrecoverable error, exit code 1
ERROR:root:-100
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/excalibur/tasks.py", line 44, in split
    with Ghostscript(*gs_call, stdout=null) as gs:
  File "/usr/local/lib/python3.7/site-packages/camelot/ext/ghostscript/__init__.py", line 93, in Ghostscript
    stderr=kwargs.get('stderr', None))
  File "/usr/local/lib/python3.7/site-packages/camelot/ext/ghostscript/__init__.py", line 39, in __init__
    rc = gs.init_with_args(instance, args)
  File "/usr/local/lib/python3.7/site-packages/camelot/ext/ghostscript/_gsprint.py", line 169, in init_with_args
    raise GhostscriptError(rc)
camelot.ext.ghostscript._gsprint.GhostscriptError: -100**

<img width="850" alt="Screen Shot 2019-07-09 at 11 18 51 am" src="https://user-images.githubusercontent.com/13301967/60852568-93ec0700-a23b-11e9-9291-ca216046546e.png">

Any help solving this would be appreciated.

**Comment by nicozhang** [comment]
![image](https://user-images.githubusercontent.com/1912794/60852960-a0b52e80-a22c-11e9-84b8-728da1a0b5f4.png)
Maybe put pdb.set_trace() in here,  check the rc value and the func args ,  will find where the problem locates.

**Comment by ac-asks** [comment]
> ![image](https://user-images.githubusercontent.com/1912794/60852960-a0b52e80-a22c-11e9-84b8-728da1a0b5f4.png)
> Maybe put pdb.set_trace() in here, check the rc value and the func args , will find where the problem locates.

Hey, thankyou!I tried your advice and am getting this output:
rc: -100
argv: (b'-q', b'-sDEVICE=png16m', b'-o', b'/usr/local/lib/python3.7/site-packages/excalibur/www/static/uploads/dcea965f-e383-4243-810c-0b3b7ddf1e25/page-1.png', b'-r300', b'/usr/local/lib/python3.7/site-packages/excalibur/www/static/uploads/dcea965f-e383-4243-810c-0b3b7ddf1e25/page-1.pdf')

I guess the rc value is wrong. I am not sure how to debug. Any suggestions / ideas?

<img width="1440" alt="Screen Shot 2019-07-09 at 12 11 54 pm" src="https://user-images.githubusercontent.com/13301967/60854250-da912f80-a242-11e9-800a-91cba764ca2e.png">

**Comment by nicozhang** [comment]
Enter s, step into libgs.gsapi_init_with_args,  check its logic, and the return value.
I met some problem too.  The gs can not decode all pdfs, some kind of encrypted pdf does not work.

**Comment by ac-asks** [comment]
> Enter s, step into libgs.gsapi_init_with_args, check its logic, and the return value.
> I met some problem too. The gs can not decode all pdfs, some kind of encrypted pdf does not work.

Hey thanks. Checking it now. Weird thing is it works perfectly using the webserver and can process any PDF but can't do any PDFs when I run it locally via flask run. 

I've fed many PDFs and all of them have been dummy PDFs and not encrypted. I will report back after debugging on whether I find anything. Thank you!

**Comment by nicozhang** [comment]
I deploy a Chinese version for my personal use here http://excalibur.fusky.xyz/files. You can try your pdfs, if meet some problem, tell me :)

**Comment by ac-asks** [comment]
> I deploy a Chinese version for my personal use here http://excalibur.fusky.xyz/files. You can try your pdfs, if meet some problem, tell me :)

Hey thank you. I've tried my PDF files on yours and it works perfectly. Did you manage to run your files via flask run on a mac?

**Comment by nicozhang** [comment]
> Hey

develop on Mac, deploy on ubuntu. Python on Ubuntu is 3.7.2, Ghostscript 9.26 (2018-11-20)

**Comment by hariteja97** [comment]
@vinayak-mehta  Please help me as I'm facing the same issue in my windows system. its windows 8.1

**Comment by 1andox** [comment]
Has anyone found a solution by any chance? Excalibur used to work beautifully on my old machine. When I got a new laptop and tried to install again I ran into several problems including having to downgrade werkzeug and flask. When I finally managed to get excalibur webserver working I ran into the same exact problem as OP. I miss using excalibur :( - camelot appears to still be working beautifully.
