### ISSUE TITLE
page : Refresh !!!

### ISSUE THREAD

**Issue by yuanwu-bujin** [camelot-dev/excalibur#69]
Refresh!
Please wait while the pages are converted to images. Refresh again in some time.
![捕获](https://user-images.githubusercontent.com/52151426/64405575-15340e80-d0b2-11e9-9ac7-217cea3e7b2b.JPG)

**Comment by rohitspace** [comment]
I am stuck at the Refresh page. 
![Capture](https://user-images.githubusercontent.com/40601559/65767667-1eae1500-e14c-11e9-8a53-1cfbdcaae441.JPG)

Please solve issue

**Comment by vinayak-mehta** [comment]
Can you please post the traceback you got on the console where you ran `excalibur webserver`?

**Comment by robroc** [comment]
I'm also getting this error. In two PDFs, the program gets stuck on this refresh page.

It works when you re-extract the data and choose Stream instead of Lattice. It would be helpful to have a warning about this.

File attached. 
[2004d.pdf](https://github.com/camelot-dev/excalibur/files/3970023/2004d.pdf)
Pages 10 and 12.

Full trace:

```
ERROR:root:At least one sheet must be visible
Traceback (most recent call last):
  File "c:\users\beto\appdata\local\continuum\miniconda3\envs\data\lib\site-packages\excalibur\tasks.py", line 123, in extract
    tables.export(f_datapath, f=f, compress=True)
  File "c:\users\beto\appdata\local\continuum\miniconda3\envs\data\lib\site-packages\camelot\core.py", line 746, in export
    writer.save()
  File "c:\users\beto\appdata\local\continuum\miniconda3\envs\data\lib\site-packages\pandas\io\excel.py", line 1228, in save
    return self.book.save(self.path)
  File "c:\users\beto\appdata\local\continuum\miniconda3\envs\data\lib\site-packages\openpyxl\workbook\workbook.py", line 397, in save
    save_workbook(self, filename)
  File "c:\users\beto\appdata\local\continuum\miniconda3\envs\data\lib\site-packages\openpyxl\writer\excel.py", line 294, in save_workbook
    writer.save()
  File "c:\users\beto\appdata\local\continuum\miniconda3\envs\data\lib\site-packages\openpyxl\writer\excel.py", line 276, in save
    self.write_data()
  File "c:\users\beto\appdata\local\continuum\miniconda3\envs\data\lib\site-packages\openpyxl\writer\excel.py", line 90, in write_data
    archive.writestr(ARC_WORKBOOK, writer.write())
  File "c:\users\beto\appdata\local\continuum\miniconda3\envs\data\lib\site-packages\openpyxl\workbook\_writer.py", line 149, in write
    self.write_views()
  File "c:\users\beto\appdata\local\continuum\miniconda3\envs\data\lib\site-packages\openpyxl\workbook\_writer.py", line 136, in write_views
    active = get_active_sheet(self.wb)
  File "c:\users\beto\appdata\local\continuum\miniconda3\envs\data\lib\site-packages\openpyxl\workbook\_writer.py", line 34, in get_active_sheet
    raise IndexError("At least one sheet must be visible")
IndexError: At least one sheet must be visible
```

**Comment by hirensuraiya** [comment]
Mine's stuck on refresh too

Traceback (most recent call last):
  File "c:\users\______\appdata\local\programs\python\python38-32\lib\site-packages\excalibur\tasks.py", line 44, in split
    with Ghostscript(*gs_call, stdout=null) as gs:
  File "c:\users\______\appdata\local\programs\python\python38-32\lib\site-packages\camelot\ext\ghostscript\__init__.py", line 90, in Ghostscript
    return __Ghostscript(
  File "c:\users\______\appdata\local\programs\python\python38-32\lib\site-packages\camelot\ext\ghostscript\__init__.py", line 39, in __init__
    rc = gs.init_with_args(instance, args)
  File "c:\users\______\appdata\local\programs\python\python38-32\lib\site-packages\camelot\ext\ghostscript\_gsprint.py", line 169, in init_with_args
    rc = libgs.gsapi_init_with_args(instance, len(argv), c_argv)
OSError: exception: access violation writing 0x00000080

**Comment by hirensuraiya** [comment]
Updated to version 0.4.3
Sill stuck and shows as processing

`127.0.0.1 - - [04/Apr/2020 17:42:01] "GET /workspaces/d007506c-9326-45cb-8e67-53dd74397b94 HTTP/1.1" 200 -
127.0.0.1 - - [04/Apr/2020 17:42:02] "GET /workspaces/d007506c-9326-45cb-8e67-53dd74397b94 HTTP/1.1" 200 -
127.0.0.1 - - [04/Apr/2020 17:42:02] "GET /workspaces/d007506c-9326-45cb-8e67-53dd74397b94 HTTP/1.1" 200 -
127.0.0.1 - - [04/Apr/2020 17:42:03] "GET /workspaces/d007506c-9326-45cb-8e67-53dd74397b94 HTTP/1.1" 200 -
127.0.0.1 - - [04/Apr/2020 17:42:04] "GET /workspaces/d007506c-9326-45cb-8e67-53dd74397b94 HTTP/1.1" 200 -
ERROR:root:exception: access violation writing 0x00000080
Traceback (most recent call last):
  File "c:\users\_\appdata\local\programs\python\python38-32\lib\site-packages\excalibur\tasks.py", line 56, in split
    with Ghostscript(*gs_call, stdout=null) as gs:
  File "c:\users\_\appdata\local\programs\python\python38-32\lib\site-packages\camelot\ext\ghostscript\__init__.py", line 90, in Ghostscript
    return __Ghostscript(
  File "c:\users\_\appdata\local\programs\python\python38-32\lib\site-packages\camelot\ext\ghostscript\__init__.py", line 39, in __init__
    rc = gs.init_with_args(instance, args)
  File "c:\users\_\appdata\local\programs\python\python38-32\lib\site-packages\camelot\ext\ghostscript\_gsprint.py", line 169, in init_with_args
    rc = libgs.gsapi_init_with_args(instance, len(argv), c_argv)
OSError: exception: access violation writing 0x00000080`

**Comment by mikes2nd** [comment]
All pdfs stuck in refresh... 

![Untitled](https://user-images.githubusercontent.com/12437703/86524533-b7935e80-be49-11ea-8237-6faffe27f563.jpg)

**Comment by ragsta** [comment]
same as above, stuck on every pdf.
![image](https://user-images.githubusercontent.com/12233725/88212471-9d35ef00-cc57-11ea-8afe-f39842ff8cf9.png)
