### ISSUE TITLE
 Unrecoverable error, exit code 1

### ISSUE THREAD

**Issue by manigandan-dorairaj** [camelot-dev/excalibur#78]
I am getting this error in the command prompt after uploading any PDF.
The webpage shows Refresh message but nothing happens after that.

```
127.0.0.1 - - [25/Oct/2019 16:41:51] "GET /static/css/vendor/jquery-ui.structure.min.css HTTP/1.1" 200 -
GPL Ghostscript 9.27: Unrecoverable error, exit code 1
ERROR:root:-100
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\site-packages\excalibur\tasks.py", line 44, in split
    with Ghostscript(*gs_call, stdout=null) as gs:
  File "c:\program files (x86)\python37-32\lib\site-packages\camelot\ext\ghostscript\__init__.py", line 95, in Ghostscript
    stderr=kwargs.get("stderr", None),
  File "c:\program files (x86)\python37-32\lib\site-packages\camelot\ext\ghostscript\__init__.py", line 39, in __init__
    rc = gs.init_with_args(instance, args)
  File "c:\program files (x86)\python37-32\lib\site-packages\camelot\ext\ghostscript\_gsprint.py", line 173, in init_with_args
    raise GhostscriptError(rc)
camelot.ext.ghostscript._gsprint.GhostscriptError: -100
```

**Comment by vinayak-mehta** [comment]
Too less information to reproduce bug.
