### ISSUE TITLE
Error:root:name 'self' is not defined

### ISSUE THREAD

**Issue by rrapstine** [camelot-dev/excalibur#79]
I am attempting to upload a PDF and have excalibur parse through all pages. I am taken to the refresh page, where nothing happens no matter what I do. Terminal output shows this...

`ERROR:root:name 'self' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/excalibur/tasks.py", line 27, in split
    extract_pages, total_pages = get_pages(file.filepath, file.pages)
  File "/usr/local/lib/python3.7/site-packages/excalibur/utils/task.py", line 35, in get_pages
    infile.decrypt(self.password)`

I am on version 0.4.2, which is what pip installed by default just a few minutes ago. Please advise.

**Comment by vinayak-mehta** [comment]
Looks like a bug.
