### ISSUE TITLE
How to change the default port

### ISSUE THREAD

**Issue by chunlei2** [camelot-dev/excalibur#81]
Hi, #32 #33 Related to these two issues. Still don't know how to change the default port. I was using excalibular 0.4.2. I changed the web_server_port in default_excalibur.cfg, but doesn't solve this problem. The error message is as below:
```
* Serving Flask app "excalibur.www.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "c:\apps\anaconda3\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\apps\anaconda3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cliu\Desktop\demo\table\excaliburPython\Scripts\excalibur.exe\__main__.py", line 7, in <module>
  File "c:\users\cliu\desktop\demo\table\excaliburpython\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\cliu\desktop\demo\table\excaliburpython\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\cliu\desktop\demo\table\excaliburpython\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\cliu\desktop\demo\table\excaliburpython\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\cliu\desktop\demo\table\excaliburpython\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\cliu\desktop\demo\table\excaliburpython\lib\site-packages\excalibur\cli.py", line 60, in webserver
    use_reloader=False)
  File "c:\users\cliu\desktop\demo\table\excaliburpython\lib\site-packages\flask\app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "c:\users\cliu\desktop\demo\table\excaliburpython\lib\site-packages\werkzeug\serving.py", line 1010, in run_simple
    inner()
  File "c:\users\cliu\desktop\demo\table\excaliburpython\lib\site-packages\werkzeug\serving.py", line 963, in inner
    fd=fd,
  File "c:\users\cliu\desktop\demo\table\excaliburpython\lib\site-packages\werkzeug\serving.py", line 806, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "c:\users\cliu\desktop\demo\table\excaliburpython\lib\site-packages\werkzeug\serving.py", line 699, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "c:\apps\anaconda3\Lib\socketserver.py", line 453, in __init__
    self.server_bind()
  File "c:\apps\anaconda3\Lib\http\server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "c:\apps\anaconda3\Lib\socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```

**Comment by mani2106** [comment]
Excalibur initializes a config file when you try to run for the first time, you can do that with
`excalibur initdb` [from here,](https://excalibur-py.readthedocs.io/en/master/#using-excalibur) If you are doing this for the first time, You'll get a message that the config was created on some PATH. The changes can be done there as mentioned in **Changes to make in config**, but if you cannot find it follow the instruction in **Finding the config file** to find the actual config.

### Finding the config file
Inside the Excalibur library folder, there would be a file named `configuration.py`, try to print the variable named `EXCALIBUR_CONFIG`, then again try to run the webserver with `excalibur webserver`,
You will see your print statement executed and revealing the actual config file, where the host and port comes from, it would be something like

### Changes to make in config
```
[webserver]
# The host interface on which to listen.
# 127.0.0.1 means the webserver will only respond to requests from the local machine.
web_server_host = 127.0.0.1

# The port on which to run the webserver.
web_server_port = 5000
```
Change the port and host there and run the `excalibur webserver` command.

There should be a better way to do this but I couldn't find any.

**Comment by chunlei2** [comment]
Thanks, it worked!
